const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxRight
	];
};
self.C3_JsPropNameTable = [
	{Sine: 0},
	{GameOverText: 0},
	{HighScoreText: 0},
	{ScoreText: 0},
	{GameOverText2: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Food: 0},
	{GameOverBack: 0},
	{PlayArea: 0},
	{n: 0},
	{PrevX: 0},
	{PrevY: 0},
	{Snake: 0},
	{MyX: 0},
	{MyY: 0},
	{Spot: 0},
	{FSnake: 0},
	{XX: 0},
	{YY: 0},
	{SpotSize: 0},
	{SnakeStart: 0},
	{SnakeNum: 0},
	{Starts: 0},
	{MoveDirection: 0},
	{MoveRate: 0},
	{MoveFlag: 0},
	{Score: 0},
	{HighScore: 0},
	{GameOver: 0},
	{Left_: 0},
	{Right_: 0},
	{Top_: 0},
	{Bottom_: 0},
	{UID: 0}
];

self.InstanceType = {
	GameOverText: class extends self.ISpriteFontInstance {},
	HighScoreText: class extends self.ISpriteFontInstance {},
	ScoreText: class extends self.ISpriteFontInstance {},
	GameOverText2: class extends self.ISpriteFontInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Food: class extends self.ISpriteInstance {},
	GameOverBack: class extends self.ITiledBackgroundInstance {},
	PlayArea: class extends self.I9PatchInstance {},
	Snake: class extends self.ISpriteInstance {},
	Spot: class extends self.ISpriteInstance {},
	FSnake: class extends self.ISpriteInstance {}
}